baseURL: 'https://kisv-workshop.github.io/'
languageCode: 'en-us'
title: 'KISV Workshop'

params:
  ShowReadingTime: true
  ShowFullTextinRSS: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: organizers
      name: Organizers
      url: /organizers
      weight: 20
    - identifier: program
      name: Program
      url: /program
      weight: 30

# Allow raw HTML in content
markup:
  goldmark:
    renderer:
      unsafe: true

